from google.cloud import speech
import os

_BASE_DIR = os.path.dirname(os.path.abspath(__file__))
_KEY_PATH = os.path.join(_BASE_DIR, "google_key.json")

# Initialize client using the specific JSON key file gracefully
client = None
try:
    client = speech.SpeechClient.from_service_account_file(_KEY_PATH)
    print("[speech_service] Google Cloud Speech API Initialized")
except Exception as e:
    print(f"[speech_service] WARNING: Could not initialize Google Cloud Speech API. {e}")

def detect_speech(audio_bytes):
    if client is None:
        raise RuntimeError("Google Cloud Speech client is not initialized. Ensure google_key.json is present.")

    audio = speech.RecognitionAudio(content=audio_bytes)

    # Note: Using WEBM_OPUS as generated by react-media-recorder
    config = speech.RecognitionConfig(
        encoding=speech.RecognitionConfig.AudioEncoding.WEBM_OPUS,
        sample_rate_hertz=48000,
        language_code="en-IN",
        alternative_language_codes=["hi-IN", "te-IN"],
    )

    response = client.recognize(config=config, audio=audio)

    text = ""
    for result in response.results:
        text += result.alternatives[0].transcript

    return text
